name: Finance bot CI

on:
  push:
    branches:
      - main
#   pull_request:
#     branches:
#       - master

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: docker build -t finance-bot .
      - name: Tags
        run: |
          docker tag finance-bot ${{ secrets.DOCKER_USER }}/finance-bot:${{ github.sha }}
          docker tag finance-bot ${{ secrets.DOCKER_USER }}/finance-bot:latest
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/finance-bot:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/finance-bot:latest
